AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  accountC
  SAM Template for accountC containing Private API Gateway, with lambda integration.

Parameters:
  ########### Parameters ###########
  CentralAccountVpcID:
    Type: String
    Description: The ID of the VPC Endpoint you want to use from the Central Account
  BedrockRegion:
    Type: String
    Default: us-east-1
    Description: Region where Amazon Titan Image Generator G1 model is enabled.

Resources:
  ########### Private API Gateway ###########
  PrivateApi:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration: PRIVATE
      StageName: Prod
      AlwaysDeploy: true
      DefinitionBody:
        openapi: "3.0.1"
        info:
          version: "1.0"
          title: !Sub "PrivateApi-${AWS::StackName}"
        x-amazon-apigateway-binary-media-types:
          - "*/*"
        paths:
          /:
            post:
              responses:
                "200":
                  description: "200 response"
              x-amazon-apigateway-integration:
                httpMethod: "POST"
                uri: 
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations
                passthroughBehavior: "when_no_match"
                type: "aws_proxy"
        x-amazon-apigateway-policy:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "execute-api:Invoke"
            Resource: "execute-api:/*"
            Condition:
              StringEquals:
                aws:sourceVpc: !Ref CentralAccountVpcID

  ########### Lambda Function ###########
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub Bedrock-Lambda-${AWS::StackName}
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 29
      MemorySize: 256
      Architectures:
        - arm64
      Environment:
        Variables:
          region: !Ref BedrockRegion
      Events:
        APIRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref PrivateApi
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: !Sub arn:aws:bedrock:${BedrockRegion}::foundation-model/amazon.titan-image-generator-v2:0

Outputs:
  ########### Outputs ###########
  ApiUrl:
    Description: "API Gateway Invoke URL"
    Value: !Sub https://${PrivateApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
