AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  (uksb-1tthgi812) (tag:s3-lambda-dotnet)
  .NET Image resizing service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: PassThrough
    Timeout: 10
    Runtime: dotnet6

Resources:
  ## Source S3 bucket
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "imageresizer-source-${AWS::AccountId}"
  ## Destination S3 bucket
  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "imageresizer-destination-${AWS::AccountId}"

  ResizerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ImageResize/
      Handler: ImageResize::ImageResize.Function::FunctionHandler
      MemorySize: 2048
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: 'images/'
                  - Name: suffix
                    Value: '.jpeg'
        Environment:
          Variables:
            SOURCE_BUCKET: !Ref SourceBucket
            DESTINATION_BUCKET: !Ref DestinationBucket
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub arn:aws:s3:::imageresizer-source-${AWS::AccountId}/*
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub arn:aws:s3:::imageresizer-destination-${AWS::AccountId}/*

Outputs:
  SourceBucketName:
    Value: !Ref SourceBucket
    Description: S3 Source Bucket for incoming images
   DestinationBucketName:
    Value: !Ref DestinationBucket
    Description: S3 Destination Bucket for resized images
  FunctionArn:
    Value: !Ref ResizerFunction
    Description: ResizerFunction function Arn
